pipeline{
    agent any
    
    stages{
        stage("Print"){
            steps{
                echo "Your selected operation is: ${Select_Operation} and Value is: ${Options}"
            }
        }
    }
}
